const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({args:['--use-gl=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});const p=await b.newPage({viewport:{width:700,height:520}});
await p.addInitScript(()=>{window.requestAnimationFrame=()=>0;});
const errs=[];p.on('pageerror',e=>errs.push('PAGE '+e.message));p.on('console',m=>{if(m.type()==='error')errs.push('CONS '+m.text())});
await p.goto('file://'+process.argv[2]);await p.waitForTimeout(3000);const out=process.argv[3];
const tick=n=>p.evaluate(n=>{__tick(n);},n);
const down=c=>p.evaluate(c=>dispatchEvent(new KeyboardEvent('keydown',{code:c,key:c})),c);
const up=c=>p.evaluate(c=>dispatchEvent(new KeyboardEvent('keyup',{code:c,key:c})),c);
const tap=async(c,hold=3)=>{await down(c);await tick(hold);await up(c);await tick(12);};
const type=async s=>{for(const ch of s)await tap(ch===' '?'Space':'Key'+ch.toUpperCase(),2);};
const st=()=>p.evaluate(()=>{const {G,P}=__dbg();return {state:G.state,over:G.over,scroll:G.scroll,lvl:P.lvl,rockets:P.rockets,lives:G.lives,cheater:G.cheater,info:G.info,frame:G.frame,lines:__dbg().CON.lines,input:__dbg().CON.input};});
await p.evaluate(()=>{__lv(0);__dbg().G.state='play';});await tick(200);
await tick(300);const cmd=async c=>{await type(c);await tap('Enter',2);await tick(40);};
await tap('Tab',4);await tick(20);
const en0=await p.evaluate(()=>__dbg().G.enemies.length);
for(const c of ['katakis','zerbiebomb','merry xmas','crazy volcanos','bullettime mode on','the barrens','silkworm','master of puppets'])await cmd(c);
console.log(JSON.stringify(await st()), 'enemies before',en0);
await tap('Tab',4);await tick(60);
console.log('after', await p.evaluate(()=>{const {G,P,CON}=__dbg();return JSON.stringify({en:G.enemies.length,shots:G.shots.filter(s=>s.type===0).length,ship:CON.ship,bullet:CON.bullet,xmas:CON.xmas,shield:P.shieldOn,rockets:P.rockets,lives:G.lives});}));
await p.screenshot({path:out+'/con3.png',clip:{x:30,y:20,width:640,height:480}});
await tap('Tab',4);await tick(20);await cmd('scott me up beamy');await tap('Tab',4);await tick(5);console.log('scroll',JSON.stringify((await st()).scroll));
await tap('Tab',4);await tick(20);await cmd('pfundi');await tap('Tab',4);await tick(700);console.log('pfundi',JSON.stringify(await p.evaluate(()=>{const {G}=__dbg();return {go:G.go,lives:G.lives,state:G.state};})));
console.log(errs.slice(0,5).join('\n')||'no errors');await b.close();})();
